import Head from "next/head";
import Link from "next/link";

// import Image from "next/image";
// import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>next-mdx1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div>hello</div>
        <ul>
          <li>
            <Link href={"mdx1"}>mdx1</Link>
          </li>
          <li>
            <Link href={"mdx1a"}>mdx1a</Link>
          </li>
        </ul>
      </main>
    </>
  );
}
