import Head from "next/head";
import Link from "next/link";

// import Image from "next/image";
// import styles from "@/styles/Home.module.css";

function Links({ links }: { links: string[] }) {
  return (
    <ul>
      {links.map((link) => (
        <li>
          <Link href={link}>{link}</Link>
        </li>
      ))}
    </ul>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>next-mdx1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <h1>next-mdx1</h1>
        <Links links={["mdx1", "mdx1a", "mdx2", "mdx3"]} />
      </main>
    </>
  );
}
